# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/59ef81c7-c351-4229-8910-092e2dd0ca14";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "space_cache=v2"
    ];
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/19a86e65-d9a6-4f40-bcd9-5edd3dcb24bd";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/59ef81c7-c351-4229-8910-092e2dd0ca14";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "space_cache=v2"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/59ef81c7-c351-4229-8910-092e2dd0ca14";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "space_cache=v2"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/59ef81c7-c351-4229-8910-092e2dd0ca14";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "space_cache=v2"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/59ef81c7-c351-4229-8910-092e2dd0ca14";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "compress=zstd:1"
      "noatime"
      "ssd"
      "space_cache=v2"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6E4C-5CE4";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
