keys:
  - &admin1 age15lcvjk4vayexm8gwtqa5avpzpk7sxq89ej9z6pdzyajfmhv04spsekh8ps
  - &idir age1tz0vdvscgsfemxmh29hytr3e6fp0qwwgn7wjs64kfcwmen88nyhs9qzjkd
  - &heibohre age1ea0ty53kq56x6ssyhgx4sp68c36ahrw455lq42v4x8wdenhg6usqfvkvrp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin1
      - *idir
      - *heibohre
