keys:
  - &user_ryan age15lcvjk4vayexm8gwtqa5avpzpk7sxq89ej9z6pdzyajfmhv04spsekh8ps
  - &host_idir age1tz0vdvscgsfemxmh29hytr3e6fp0qwwgn7wjs64kfcwmen88nyhs9qzjkd
  - &host_aquime age1ekkskexkzylhtwujzj74h9uam0q8ndgyqdnkzzets69s6mr5ddgq89tlzy
  - &host_masaq age1t40qjw9s87y9ul7g0k5gvn70urlv070f6qveap2xc09sxtatsydsgm8xq9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_ryan
      - *host_idir
      - *host_aquime
      - *host_masaq
